### ISSUE TITLE
apollo client on infinite loop when used with mantra-redux

### ISSUE THREAD

**Issue by purplecones** [sammkj/mantra-redux#3]
When I use this package to include apollo client, it goes into an infiintae loop

``` javascript
const Client = configureGraphQLClient();
const logger = createLogger();
const middlewares = [
  thunk,
  logger,
  Client.middleware(),
];

const reducers = {
  // other reducers
  apollo: Client.reducer(),
};

const context = initContext({ Client });
const app = createApp(context);
app.loadMiddlewares([
  redux({
    reducers,
    middlewares,
  }),
]);
app.loadModule(coreModule);
// load more modules
app.init();
```

Example Container:

``` javascript
const mapQueryToProps = ({ context }, onData) => {
  const { Client } = context();

  const query = `{
    investmentAccounts {
      userId
      streetAddress1
    }
  }`;

  const taggedQuery = gql`${query}`;

  Client.query({
    query: taggedQuery,
    forceFetch: true,
  }).then((graphQLResult) => {
    onData(null, {
      data: graphQLResult.data,
      errors: graphQLResult.errors,
    });
  }).catch((ex) => {
    onData(ex);
  });
};
```

However, If I use the mantra-apollo package instead, it is fine

``` javascript
app.loadMiddlewares([
  redux({
    reducers,
    middlewares,
  }),
  apollo({
    clientName: 'Client',
  }),
]);
```

Not too familiar with the internals of apollo client yet, but it appears to be an issue with [mantra-redux](https://github.com/sammkj/mantra-redux) when using the apollo middleware. I'd prefer to use it that way so that there is one store instead of two with the example directly above.

**Comment by kokjinsam** [comment]
Probably [this line](https://github.com/sammkj/mantra-redux/blob/master/src/index.js#L32) is causing the problem. I don't have my computer with atm. I will patch a fix asap.

**Comment by kokjinsam** [comment]
Also, do you have a sample that I can work with?

**Comment by purplecones** [comment]
I don't. The one above is part of a larger private app but I'll try to put together a basic example to replicate issue.

**Comment by kokjinsam** [comment]
hey @purplecones , I'm sorry. Unfortunately, I was not able to reproduce the error [here](https://github.com/sammkj/meteor-1.3-todo). If you can post a repro, then that would be awesome!

**Comment by purplecones** [comment]
I can try to reproduce with your repo. However, I'm getting this error when running it:

```
Cannot read property 'allTodos' of undefined 
TypeError: Cannot read property 'allTodos' of undefined
    at http://localhost:3000/app/app.js?hash=d6a13cce114a77531a9c3292230f2dc67f46bdb0:464:32
    at http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:1105:22
```

![simple_todo](https://cloud.githubusercontent.com/assets/136654/16473575/650110e0-3e3c-11e6-82fd-c04177f19e7c.png)

![localhost_3000_graphql_query__7b_0a__alltodos__7b_0a_____id_0a____todo_0a___7d_0a_7d](https://cloud.githubusercontent.com/assets/136654/16473568/3c1c4d5c-3e3c-11e6-8a42-807dbbd8c661.png)

**Comment by purplecones** [comment]
yea it works on your repo... hmm

**Comment by kokjinsam** [comment]
The only thing that I think might be different is your `configureGraphQLClient()`.

**Comment by purplecones** [comment]
The problem was elsewhere in one of my layout components that was for some reason triggering a re-render. Removing that code block fixed my issued. Thanks
